// lit-simple-app/src/CalcOpButton.js
import { html, css, LitElement } from 'lit'

export class CalcOpButton extends LitElement {
  static get properties() {
    return {
      label: { type: String },
    }
  }

  // constructor() {
  //   super()
  //   this.setAttribute("class", "CalcOpButton")
  // }

  render() {
    return html`
      <button class="CalcOpButton">${this.label}</button>
    `
  }
}

window.customElements.define('my-calc-op-button', CalcOpButton)

// react-calc-ts/src/CalcOpButton.tsx
import React from 'react'

interface Props {
  label: string
  onClick: () => void
}

export default class CalcOpButton extends React.Component<Props, {}> {
  constructor(props: Props) {
    super(props)
  }
  render() {
    return (
      <button className="CalcOpButton" {...this.props}>{this.props.label}</button>
    )
  }
}
