// vue3-composition-api/src/components/CalcApp.vue
<template>
  <span class="CalcApp">
    p {{ax_r}},{{op_r}},{{bx_r}}({{cx_r}})
    <CalcDisplay>{{resultString}}</CalcDisplay>
    <div className="CalcNumButtons">
      <template v-if="isClearHandle">
        <CalcDarkButton label="C"  @click="onClearHandle" />
      </template>
      <template v-else>
        <CalcDarkButton label="AC" @click="onAllClearHandle" />
      </template>
      <CalcDarkButton label="±" @click="onSignToggle" />
      <CalcDarkButton label="％" @click="onParcentage" />
      <CalcOpButton   label="÷" @click="onSetOpHandle('/')" />
      <CalcNumButton  label="7"  @click="onNumberClickHandle(7)" />
      <CalcNumButton  label="8"  @click="onNumberClickHandle(8)" />
      <CalcNumButton  label="9"  @click="onNumberClickHandle(9)" />
      <CalcOpButton   label="×" @click="onSetOpHandle('*')" />
      <CalcNumButton  label="4"  @click="onNumberClickHandle(4)" />
      <CalcNumButton  label="5"  @click="onNumberClickHandle(5)" />
      <CalcNumButton  label="6"  @click="onNumberClickHandle(6)" />
      <CalcOpButton   label="-"  @click="onSetOpHandle('-')" />
      <CalcNumButton  label="1"  @click="onNumberClickHandle(1)" />
      <CalcNumButton  label="2"  @click="onNumberClickHandle(2)" />
      <CalcNumButton  label="3"  @click="onNumberClickHandle(3)" />
      <CalcOpButton   label="+"  @click="onSetOpHandle('+')" />
      <CalcNumButton  label="0"  @click="onNumberClickHandle(0)" class="is_2x" />
      <CalcNumButton  label="00" @click="onZeroZeroClick" />
      <CalcOpButton   label="="  @click="onEqualHandle" />
    </div>
  </span>
</template>

<script>
import { ref, computed, watch } from 'vue'

import CalcNumButton  from "./CalcNumButton.vue"
import CalcOpButton   from "./CalcOpButton.vue"
import CalcDarkButton from "./CalcDarkButton.vue"
import CalcDisplay    from "./CalcDisplay.vue"
import "./CalcApp.css"

export default {
  name: "CalcApp",
  components: {
    CalcNumButton,
    CalcOpButton,
    CalcDarkButton,
    CalcDisplay,
  },
  setup() {
    const ax_r = ref(0)
    const bx_r = ref(null)
    const cx_r = ref(null)
    const op_r = ref(null)

    watch(ax_r, (new_v, old_v) => document.title = new_v.toString())

    function onNumberClickHandle(plus_value) {
      if (op_r.value == null) {
        ax_r.value = ax_r.value * 10 + plus_value
      } else {
        bx_r.value = bx_r.value * 10 + plus_value
      }
    }

    function onZeroZeroClick() {
      onNumberClickHandle(0)
      onNumberClickHandle(0)
    }

    function onClearHandle() {
      bx_r.value = null
    }

    function onAllClearHandle() {
      ax_r.value = 0
      bx_r.value = null
      cx_r.value = null
      op_r.value = null
    }

    function onSetOpHandle(v) {
      if (bx_r.value != null) {
        calcUpdate()
      }
      op_r.value = v
    }

    function onEqualHandle() {
      if (op_r.value != null) {
        bx_r.value ??= cx_r.value ?? ax_r.value
        calcUpdate()
      }
    }

    function calcUpdate() {
      const value = calcUpdate2(ax_r.value, bx_r.value, op_r.value)
      ax_r.value = value
      cx_r.value = bx_r.value
      bx_r.value = null
    }

    function calcUpdate2(ax, bx, op) {
      let value = null;
      if (false) {
      } else if (op === "+") {
        value = ax + bx
      } else if (op === "-") {
        value = ax - bx
      } else if (op === "*") {
          value = ax * bx
      } else if (op === "/") {
        value = ax / bx
      }
      return Math.trunc(value)
    }

    function onSignToggle() {
      if (bx_r.value != null) {
        bx_r.value = -bx_r.value
      } else if (ax_r.value != null) {
        ax_r.value = -ax_r.value
      }
    }

    function onParcentage() {
      if (bx_r.value != null) {
        bx_r.value = bx_r.value / 100
      } else if (ax_r.value != null) {
        ax_r.value = ax_r.value / 100
      }
    }

    // computed

    const isClearHandle = computed(() => bx_r.value != null)

    const resultString = computed(() => {
      let str = null
      if (bx_r.value != null) {
        str = bx_r
      } else if (ax_r.value != null) {
        str = ax_r
      }
      return str
    })

    return {
      ax_r,
      bx_r,
      cx_r,
      op_r,
    }
  },
}
</script>

<style>
</style>

// svelte-calc-js/src/lib/CalcApp.svelte
<script>
  import CalcNumButton  from "./CalcNumButton.svelte"
  import CalcOpButton   from "./CalcOpButton.svelte"
  import CalcDarkButton from "./CalcDarkButton.svelte"
  import CalcDisplay    from "./CalcDisplay.svelte"
  import "./CalcApp.css"

  let ax_r = 0
  let bx_r = null
  let cx_r = null
  let op_r = null

  $: {
    document.title = ax_r.toString()
  }

  function onNumberClickHandle(plus_value) {
    if (op_r == null) {
      ax_r = ax_r * 10 + plus_value
    } else {
      bx_r = bx_r * 10 + plus_value
    }
  }

  function onZeroZeroClick() {
    onNumberClickHandle(0)
    onNumberClickHandle(0)
  }

  function onClearHandle() {
    bx_r = null
  }

  function onAllClearHandle() {
    ax_r = 0
    bx_r = null
    cx_r = null
    op_r = null
  }

  function onSetOpHandle(v) {
    if (bx_r != null) {
      calcUpdate()
    }
    op_r = v
  }

  function onEqualHandle() {
    if (op_r != null) {
      bx_r ??= cx_r ?? ax_r
      calcUpdate()
    }
  }

  function calcUpdate() {
    const value = calcUpdate2(ax_r, bx_r, op_r)
    ax_r = value
    cx_r = bx_r
    bx_r = null
  }

  function calcUpdate2(ax, bx, op) {
    let value = null;
    if (false) {
    } else if (op === "+") {
      value = ax + bx
    } else if (op === "-") {
      value = ax - bx
    } else if (op === "*") {
      value = ax * bx
    } else if (op === "/") {
      value = ax / bx
    }
    return Math.trunc(value)
  }

  function onSignToggle() {
    if (bx_r != null) {
      bx_r = -bx_r
    } else if (ax_r != null) {
      ax_r = -ax_r
    }
  }

  function onParcentage() {
    if (bx_r != null) {
      bx_r = bx_r / 100
    } else if (ax_r != null) {
      ax_r = ax_r / 100
    }
  }

  // computed

  $: isClearHandle = bx_r != null

  $: resultString = (() => {
    let str = null
    if (bx_r != null) {
      str = bx_r
    } else if (ax_r != null) {
      str = ax_r
    }
    return str
  })();
</script>

<span class="CalcApp">
  <!-- <p>{ax_r},{op_r},{bx_r}({cx_r})</p> -->
  <CalcDisplay>{resultString}</CalcDisplay>
  <div class="CalcNumButtons">
    {#if isClearHandle}
      <CalcDarkButton label="C"  on:click={() => onClearHandle()} />
    {:else}
      <CalcDarkButton label="AC" on:click={() => onAllClearHandle()} />
    {/if}
    <CalcDarkButton label="±" on:click={() => onSignToggle()} />
    <CalcDarkButton label="％" on:click={() => onParcentage()} />
    <CalcOpButton   label="÷" on:click={() => onSetOpHandle('/')} />
    <CalcNumButton  label="7"  on:click={() => onNumberClickHandle(7)} />
    <CalcNumButton  label="8"  on:click={() => onNumberClickHandle(8)} />
    <CalcNumButton  label="9"  on:click={() => onNumberClickHandle(9)} />
    <CalcOpButton   label="×" on:click={() => onSetOpHandle('*')} />
    <CalcNumButton  label="4"  on:click={() => onNumberClickHandle(4)} />
    <CalcNumButton  label="5"  on:click={() => onNumberClickHandle(5)} />
    <CalcNumButton  label="6"  on:click={() => onNumberClickHandle(6)} />
    <CalcOpButton   label="-"  on:click={() => onSetOpHandle('-')} />
    <CalcNumButton  label="1"  on:click={() => onNumberClickHandle(1)} />
    <CalcNumButton  label="2"  on:click={() => onNumberClickHandle(2)} />
    <CalcNumButton  label="3"  on:click={() => onNumberClickHandle(3)} />
    <CalcOpButton   label="+"  on:click={() => onSetOpHandle('+')} />
    <CalcNumButton  label="0"  on:click={() => onNumberClickHandle(0)} is_wide />
    <CalcNumButton  label="00" on:click={() => onZeroZeroClick()} />
    <CalcOpButton   label="="  on:click={() => onEqualHandle()} />
  </div>

  <!-- {@debug ax_r} -->
  <!-- {@debug bx_r} -->
  <!-- {@debug cx_r} -->
  <!-- {@debug op_r} -->
</span>

<style>
</style>
