// vite-vue3/src/components/CalcApp.vue
<script setup>
import { ref, computed } from 'vue'

import CalcNumButton  from "./CalcNumButton.vue"
import CalcOpButton   from "./CalcOpButton.vue"
import CalcDarkButton from "./CalcDarkButton.vue"
import CalcDisplay    from "./CalcDisplay.vue"
import "./CalcApp.css"

const ax_value = ref(0)
const bx_value = ref(null)
const cx_value = ref(null)
const op_value = ref(null)

function onNumberClickHandle(plus_value) {
  if (op_value.value == null) {
    ax_value.value = ax_value.value * 10 + plus_value
  } else {
    bx_value.value = bx_value.value * 10 + plus_value
  }
}

function onZeroZeroClick() {
  onNumberClickHandle(0)
  onNumberClickHandle(0)
}

function onClearHandle() {
  bx_value.value = null
}

function onAllClearHandle() {
  ax_value.value = 0
  bx_value.value = null
  cx_value.value = null
  op_value.value = null
}

function onSetOpHandle(v) {
  if (bx_value.value != null) {
    calcUpdate()
  }
  op_value.value = v
}

function onEqualHandle() {
  if (op_value.value != null) {
    // bx がなければ cx か ax を設定と自然に書ける
    if (bx_value.value == null) {
      bx_value.value = cx_value.value ?? ax_value.value
    }
    // ここで bx_value.value には確実に値が入っている
    // React では入っていない
    calcUpdate()
    cx_value.value = bx_value.value
    bx_value.value = null
  }
  // // しかたなくばらして実行
  // // すでに使いにくくなっている
  //   if (op_value.value != null) {
  //     let rhv = bx_value.value ?? cx_value.value ?? ax_value.value
  //     const value = calcUpdate2(ax_value.value, rhv, op_value.value)
  //     ax_value.value = value
  //     bx_value.value = null
  //     cx_value.value = rhv
  //   }
}

function calcUpdate() {
  const value = calcUpdate2(ax_value.value, bx_value.value, op_value.value)
  ax_value.value = value
  bx_value.value = null
}

function calcUpdate2(ax, bx, op) {
  let value = null;
  if (false) {
  } else if (op === "+") {
    value = ax + bx
  } else if (op === "-") {
    value = ax - bx
  } else if (op === "*") {
      value = ax * bx
  } else if (op === "/") {
    value = ax / bx
  }
  return Math.trunc(value)
}

function onSignToggle() {
  if (bx_value.value != null) {
    bx_value.value = -bx_value.value
  } else if (ax_value.value != null) {
    ax_value.value = -ax_value.value
  }
}

function onParcentage() {
  if (bx_value.value != null) {
    bx_value.value = bx_value.value / 100
  } else if (ax_value.value != null) {
    ax_value.value = ax_value.value / 100
  }
}

// computed

const isClearHandle = computed(() => bx_value.value != null)

const resultString = computed(() => {
  let str = null
  if (bx_value.value != null) {
    str = bx_value
  } else if (ax_value.value != null) {
    str = ax_value
  }
  return str
})
</script>

<template>
  <span class="CalcApp">
    <!-- p {{ax_value}},{{op_value}},{{bx_value}} -->
    <CalcDisplay>{{resultString}}</CalcDisplay>
    <div className="CalcNumButtons">
      <template v-if="isClearHandle">
        <CalcDarkButton label="C"  @click="onClearHandle" />
      </template>
      <template v-else>
        <CalcDarkButton label="AC" @click="onAllClearHandle" />
      </template>
      <CalcDarkButton label="±" @click="onSignToggle" />
      <CalcDarkButton label="％" @click="onParcentage" />
      <CalcOpButton   label="÷" @click="onSetOpHandle('/')" />
      <CalcNumButton  label="7"  @click="onNumberClickHandle(7)" />
      <CalcNumButton  label="8"  @click="onNumberClickHandle(8)" />
      <CalcNumButton  label="9"  @click="onNumberClickHandle(9)" />
      <CalcOpButton   label="×" @click="onSetOpHandle('*')" />
      <CalcNumButton  label="4"  @click="onNumberClickHandle(4)" />
      <CalcNumButton  label="5"  @click="onNumberClickHandle(5)" />
      <CalcNumButton  label="6"  @click="onNumberClickHandle(6)" />
      <CalcOpButton   label="-"  @click="onSetOpHandle('-')" />
      <CalcNumButton  label="1"  @click="onNumberClickHandle(1)" />
      <CalcNumButton  label="2"  @click="onNumberClickHandle(2)" />
      <CalcNumButton  label="3"  @click="onNumberClickHandle(3)" />
      <CalcOpButton   label="+"  @click="onSetOpHandle('+')" />
      <CalcNumButton  label="0"  @click="onNumberClickHandle(0)" class="is_2x" />
      <CalcNumButton  label="00" @click="onZeroZeroClick" />
      <CalcOpButton   label="="  @click="onEqualHandle" />
    </div>
  </span>
</template>

<style>
</style>

// react-calc-ts-class/src/CalcApp.tsx
import React from 'react'
import CalcNumButton from "./CalcNumButton"
import CalcOpButton from "./CalcOpButton"
import CalcDarkButton from "./CalcDarkButton"
import CalcDisplay from "./CalcDisplay"

interface State {
  ax_value: any
  bx_value: any
  cx_value: any
  op_value: any
}

export default class CalcApp extends React.Component<{}, State> {
  state: State = {
    ax_value: 0,
    bx_value: null,
    cx_value: null,
    op_value: null,
  }

  onNumberClickHandle = (plus_value: any) => {
    if (this.state.op_value == null) {
      this.setState(prev => ({ax_value: prev.ax_value * 10 + plus_value}))
    } else {
      this.setState(prev => ({bx_value: prev.bx_value * 10 + plus_value}))
    }
  }

  onZeroZeroClick = () => {
    this.onNumberClickHandle(0)
    this.onNumberClickHandle(0)
  }

  onClearHandle = () => {
    this.setState({bx_value: null})
  }

  onAllClearHandle = () => {
    this.setState({ax_value: 0})
    this.setState({bx_value: null})
    this.setState({cx_value: null})
    this.setState({op_value: null})
  }

  isClearHandle = () => {
    return this.state.bx_value != null
  }

  onSetOpHandle = (op_value: any) => {
    if (this.state.bx_value != null) {
      this.calcUpdate()
    }
    this.setState({op_value: op_value})
  }

  onEqualHandle = () => {
    if (false) {
      // 次のように書きたかったが bx_value を設定しても this.stata.bx_value は更新されない
      if (this.state.op_value != null) {
        if (this.state.bx_value == null) {
          this.setState({bx_value: this.state.ax_value})
        }
        this.calcUpdate()
      }
    } else {
      // しかたなくばらして実行
      // すでに使いにくくなっている
      if (this.state.op_value != null) {
        let rhv = this.state.bx_value ?? this.state.cx_value ?? this.state.ax_value
        const value = this.calcUpdate2(this.state.ax_value, rhv, this.state.op_value)
        this.setState({ax_value: value})
        this.setState({bx_value: null})
        this.setState({cx_value: rhv})
      }
    }
  }

  calcUpdate = () => {
    const value = this.calcUpdate2(this.state.ax_value, this.state.bx_value, this.state.op_value)
    this.setState({ax_value: value})
    this.setState({bx_value: null})
  }

  calcUpdate2 = (ax: any, bx: any, op: any) => {
    let value = null;
    if (false) {
    } else if (op === "+") {
      value = ax + bx
    } else if (op === "-") {
      value = ax - bx
    } else if (op === "*") {
      value = ax * bx
    } else if (op === "/") {
      value = ax / bx
    }
    return Math.trunc(value)
  }

  onSignToggle = () => {
    if (this.state.bx_value != null) {
      this.setState({bx_value: -this.state.bx_value})
    } else if (this.state.ax_value != null) {
      this.setState({ax_value: -this.state.ax_value})
    }
  }

  onParcentage = () => {
    if (this.state.bx_value != null) {
      this.setState({bx_value: this.state.bx_value / 100})
    } else if (this.state.ax_value != null) {
      this.setState({ax_value: this.state.ax_value / 100})
    }
  }

  resultString = () => {
    let str = null
    if (this.state.bx_value != null) {
      str = this.state.bx_value
    } else if (this.state.ax_value != null) {
      str = this.state.ax_value
    }
    return str
  }

  render() {
    return (
      <div className="CalcApp">
        {/* <CalcDisplay> */}
        {/*   {(this.state.ax_value != null) && <span>{this.state.ax_value}</span>} */}
        {/*   {(this.state.op_value != null) && <span>{this.state.op_value}</span>} */}
        {/*   {(this.state.bx_value != null) && <span>{this.state.bx_value}</span>} */}
        {/* </CalcDisplay> */}

        {/* <CalcDisplay>{this.state.ax_value}, {this.state.op_value}, {this.state.bx_value} ({this.state.cx_value})</CalcDisplay> */}
        <CalcDisplay>{this.resultString()}</CalcDisplay>

        <div className="CalcNumButtons">
          {this.isClearHandle()
           ? <CalcDarkButton label="C"  onClick={this.onClearHandle} />
           : <CalcDarkButton label="AC"  onClick={this.onAllClearHandle} />
          }
          <CalcDarkButton label="±" onClick={this.onSignToggle} />
          <CalcDarkButton label="％" onClick={this.onParcentage} />
          <CalcOpButton   label="÷" onClick={() => this.onSetOpHandle("/")} />
          <CalcNumButton  label="7"  onClick={() => this.onNumberClickHandle(7)} />
          <CalcNumButton  label="8"  onClick={() => this.onNumberClickHandle(8)} />
          <CalcNumButton  label="9"  onClick={() => this.onNumberClickHandle(9)} />
          <CalcOpButton   label="×" onClick={() => this.onSetOpHandle("*")} />
          <CalcNumButton  label="4"  onClick={() => this.onNumberClickHandle(4)} />
          <CalcNumButton  label="5"  onClick={() => this.onNumberClickHandle(5)} />
          <CalcNumButton  label="6"  onClick={() => this.onNumberClickHandle(6)} />
          <CalcOpButton   label="-"  onClick={() => this.onSetOpHandle("-")} />
          <CalcNumButton  label="1"  onClick={() => this.onNumberClickHandle(1)} />
          <CalcNumButton  label="2"  onClick={() => this.onNumberClickHandle(2)} />
          <CalcNumButton  label="3"  onClick={() => this.onNumberClickHandle(3)} />
          <CalcOpButton   label="+"  onClick={() => this.onSetOpHandle("+")} />
          <CalcNumButton  label="0"  onClick={() => this.onNumberClickHandle(0)} className="CalcNumButton is_2x" />
          <CalcNumButton  label="00" onClick={this.onZeroZeroClick} />
          <CalcOpButton   label="="  onClick={this.onEqualHandle} />
        </div>
      </div>
    )
  }
}
