// svelte344-calc-app/src/App.svelte
<script>
  import CalcApp from './lib/CalcApp.svelte'
</script>

<main>
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
</main>

<svelte:head>
  <style>
    html {
      background-color: hsla(0, 0%, 20%);
    }
  </style>
</svelte:head>

<style>
  main {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin: 0.5rem;
    gap: 0.5rem;
  }
</style>

// vite-vue3-composition-api/src/App.vue
<script setup>
import CalcApp from './components/CalcApp.vue'
</script>

<template>
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
  <CalcApp />
</template>

<style>
#app {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  margin: 0.5rem;
  gap: 0.5rem;
}
html {
  background-color: hsla(0, 0%, 20%);
}
</style>
